### ISSUE TITLE
Add Cleanup events script

### ISSUE THREAD

**Issue by klippx** [klarna/phobos_db_checkpoint#11]
Would it not make perfect sense to create a Cleanup Events helper script to this repo, so it doesn't have to be implemented by the users' Phobos apps?

e.g. `bin/phobos_db_checkpoint_cleanup_events`

**Comment by tulios** [comment]
This is gray area in my opinion since the time you would keep the events might change from app to app, but we should have documented or/and an example of how to do it. We can add this as a command to `phobos_db_checkpoint` binary instead of a different binary, the command could receive the period and other options
